### ISSUE TITLE
'NoneType' object has no attribute 'startswith' occurs when querying a repository

### ISSUE THREAD

**Issue by GirlKiller512** [azmiao/github_reminder#1]
在查仓库时，出现`ERROR: 'NoneType' object has no attribute 'startswith'`错误
```
[2021-09-14 13:00:28,522 github_reminder] ERROR: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/HoshinoBot/hoshino/modules/github_reminder/__init__.py", line 38, in search_depo
    msg = create_msg(url)
  File "/root/HoshinoBot/hoshino/modules/github_reminder/get_com.py", line 75, in create_msg
    link_list, n = get_commits(html)
  File "/root/HoshinoBot/hoshino/modules/github_reminder/get_com.py", line 32, in get_commits
    if a_lable.string.startswith('from '):
AttributeError: 'NoneType' object has no attribute 'startswith'
[2021-09-14 13:00:28,523 nonebot] INFO: Message 341764145 is ignored: Handled by Hoshino
```

**Comment by azmiao** [comment]
正常来说应该不会有nonetype出现的吧，不过我测试的样本比较少倒是，能给个你报错所查的仓库链接嘛，我这边试试

**Comment by GirlKiller512** [comment]
https://github.com/Ice-Cirno/HoshinoBot

**Comment by GirlKiller512** [comment]
刚刚还查了NoneBot和go-cqhttp仓库，不过这2个没出现这个错误
目前就星乃仓库出现了

**Comment by azmiao** [comment]
> 刚刚还查了NoneBot和go-cqhttp仓库，不过这2个没出现这个错误
> 目前就星乃仓库出现了

嗯嗯，那估计内容上有点小问题，等我晚上回去改改，现在还在图书馆（）23333
