### ISSUE TITLE
好像github页面元素又变动导致插件失效了

### ISSUE THREAD

**Issue by iona-s** [azmiao/github_reminder#12]
最近又开始报错了（不清楚是不是个例）
报错内容如下
```
[2024-01-17 01:50:01,298 github_reminder_poller] ERROR: list index out of range
Traceback (most recent call last):
  File "~\hoshino\service.py", line 344, in wrapper
    ret = await func()
  File "~\hoshino\modules\github_reminder\__init__.py", line 74, in depo_commit_poller
    await poller_update(bot)
  File "~\hoshino\modules\github_reminder\com_poller.py", line 21, in poller_update
    new_time = data_list[0]['time']
IndexError: list index out of range
```
然后捣鼓了下发现`soup.text`返回的刚好是json形式的commit历史信息，
整个soup里就只有`<html><body><p>commit历史信息的json文本</p/></body></html>`，
然后便有如下可能不太靠谱的修复
`get_com.py` 29-41行替换为如下
```python
raw_info = json.loads(soup.text)
commit_infos_by_timeline = raw_info['payload']['commitGroups']
commit_counter = 0  # 记录commit数
for commit_info_by_timeline in commit_infos_by_timeline:
    commit_infos = commit_info_by_timeline['commits']
    for commit_info in commit_infos:
        commit_message = commit_info['shortMessage']
        authors_info = commit_info['authors']
        authors_name = ','.join([info['displayName'] for info in authors_info])
        raw_time = commit_info['committedDate']
        time = await change_time(raw_time)
        data_list.append({'title': commit_message, 'author': authors_name, 'time': time})
        commit_counter += 1
        if commit_counter >= 5:  # 如果要只取最近5次commit
            return data_list
```
简单测试了下应该没有什么大问题
因为对bs4不太熟悉不清楚为啥只返回了个json文本，但感觉怪怪的，可能用段时间就用不了了
更正经的修复就得重新找页面元素或者直接用github的官方api了

**Comment by azmiao** [comment]
嗯，你可以提交下pr我通过下就行，之前是api的限制太多了所以才这样用的
