### ISSUE TITLE
无法“查仓库“

### ISSUE THREAD

**Issue by WindStill** [azmiao/github_reminder#5]
![image](https://user-images.githubusercontent.com/958456/140902392-c410cb9f-e004-4670-af8d-3aa1740c4917.png)

我这边走的旁路由，github自动翻墙，访问github是没问题的。

试了下用镜像库也不行
![image](https://user-images.githubusercontent.com/958456/140901755-51750cf4-730b-4771-97bf-dcc341d53b5f.png)

**Comment by azmiao** [comment]
查的时候不需要.git的，只需要一个网页就行，你再试试看？

**Comment by WindStill** [comment]
> 查的时候不需要.git的，只需要一个网页就行，你再试试看？

不加.git的话，报错如下：
```
[2021-11-09 17:43:53,293 github_reminder] ERROR: list index out of range
Traceback (most recent call last):
  File "/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "/HoshinoBot/hoshino/modules/github_reminder/__init__.py", line 43, in search_depo
    msg = create_msg(url)
  File "/HoshinoBot/hoshino/modules/github_reminder/get_com.py", line 96, in create_msg
    link_list, n = get_commits(html)
  File "/HoshinoBot/hoshino/modules/github_reminder/get_com.py", line 68, in get_commits
    edit_html = another_list_1[0].replace(f'{other_list_1[0]}', '')
IndexError: list index out of range
```

**Comment by azmiao** [comment]
嗯嗯，这个问题是因为github源码变化了，你重新git clone一下我今天刚更新的应该就能用了

**Comment by WindStill** [comment]
> 嗯嗯，这个问题是因为github源码变化了，你重新git clone一下我今天刚更新的应该就能用了

好了。重新拉取代码没问题了

**Comment by azmiao** [comment]
ok
